# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Comment:
  fields:
    default: item_id, user_id, text, item, user
    form: item_id, user_id, text, item, user
  order_by: 
  relationships: item, user
  filters: created_at
  search: 
  application: kanban

HistoryEntry:
  fields:
    default: action, trigger_id, delta, item_id, item
    form: action, trigger_id, delta, item_id, item
  order_by: 
  relationships: item
  filters: created_at
  search: 
  application: kanban

Item:
  fields:
    default: start_date, end_date, title, text, owner_id, estimation, lane_id, position, wip_total, current_lane_entry, last_editor_id, size, lane, owner, last_editor
    form: start_date, end_date, title, text, owner_id, estimation, lane_id, wip_total, current_lane_entry, last_editor_id, size, lane, owner, last_editor
  order_by: position
  relationships: comments, history_entries, lane, last_editor, owner, statistics, versions
  filters: created_at
  search: title
  application: kanban

Lane:
  fields:
    default: title, max_items, position, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
    form: title, max_items, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
  order_by: position
  relationships: items, project, statistics, sub_lanes, super_lane
  filters: created_at
  search: title
  application: kanban

Project:
  fields:
    default: name
    form: name
  order_by: 
  relationships: backlog, lanes, livelog, parking
  filters: created_at
  search: name
  application: kanban

RestrictedLane:
  fields:
    default: title, max_items, position, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
    form: title, max_items, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
  order_by: position
  relationships: items, project, statistics, sub_lanes, super_lane
  filters: created_at
  search: title
  application: kanban

StandardLane:
  fields:
    default: title, max_items, position, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
    form: title, max_items, super_lane_id, project_id, counts_wip, warn_limit, urgent_limit, dashboard, project, super_lane
  order_by: position
  relationships: items, project, statistics, sub_lanes, super_lane
  filters: created_at
  search: title
  application: kanban

Statistic:
  fields:
    default: entry_time, leave_time, item_id, lane_id, user_id, duration, lane, item, user
    form: entry_time, leave_time, item_id, lane_id, user_id, duration, lane, item, user
  order_by: 
  relationships: item, lane, user
  filters: created_at
  search: 
  application: kanban

TypusUser:
  fields:
    default: first_name, last_name, role, email, status, token, preferences
    form: first_name, last_name, role, email, status, token, preferences
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: kanban

User:
  fields:
    default: email, last_login_at, last_login_ip, name
    form: email, last_login_at, last_login_ip, name
  order_by: 
  relationships: history_entries, items, statistics
  filters: created_at
  search: name
  application: kanban

