# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Comment: create, read, update, delete
  HistoryEntry: create, read, update, delete
  Item: create, read, update, delete
  Lane: create, read, update, delete
  Project: create, read, update, delete
  RestrictedLane: create, read, update, delete
  StandardLane: create, read, update, delete
  Statistic: create, read, update, delete
  TypusUser: create, read, update, delete
  User: create, read, update, delete