production:
  adapter: sqlite3
  database: shared/kanban_production.sqlite3
  pool: 5
  timeout: 5000
development:
  adapter: sqlite3
  database: shared/kanban_production.sqlite3
  pool: 5
  timeout: 5000 